### ISSUE TITLE
Any plan to support mac?

### ISSUE THREAD

**Issue by ianluo-align** [noamraph/nixsa#18]
It looks really nice, however I'm using a mac, any plan to support MacOS?

**Comment by noamraph** [comment]
Hi, thanks! I currently don't have plans to support MacOS, since:
1. I don't have MacOS and it seems like a lot of trouble to get a remote MacOS development environment.
2. The underlying sandboxing tool, bubblewrap, doesn't support MacOS. I don't know how hard it would be to get a similar sandbox on MacOS. I suspect it's not trivial, as nix-portable has many backends, and still no MacOS support. I found [this](https://github.com/PrismLauncher/PrismLauncher/issues/1146) which says that there exists native MacOS sandboxing. But I don't know if it's capable of mounting a `nix` directory as `/nix`.
